# spring.datasource.url=jdbc:mysql://mysqldb:3306/items
# spring.datasource.username=productuser
# spring.datasource.password=productpass123
# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect



server.port=8080
# spring.application.name=bankapp
# MySQL Database configuration
#spring.datasource.url=jdbc:mysql://backend-database.cqziqqmi6suf.us-east-1.rds.amazonaws.com:3306/backenddb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.url=jdbc:mysql://mysql:3306/backenddb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA & Hibernate configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=true
